allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - prisma
  - sharp
  - unrs-resolver
onlyBuiltDependencies:
  - '@prisma/engines'
